import type { PastBid } from "./types";

/** Static subset mimicking `bid_metadata.json` for UI until `/api/library_metadata` exists. */
export const MOCK_PAST_BIDS: PastBid[] = [
  {
    seq: 6,
    project:
      "London Borough of Haringey (Haringey Community Benefit Society), Void Repairs",
    outcome: "WON",
    bid_type: "Mini Tender",
    submitted: "2023-07-17",
    quality_score_pct: 60.5,
    quality_tier: "high_quality",
    group: "won",
    outcome_notes:
      "13 Sept 2023. Confirmed won, scored 60.5% overall.",
    questions: ["Mobilisation", "Health & Safety", "Risk Management"],
    price_quality_split: "100% Quality",
    value_gbp: 1_200_000,
    qdrant_project_name: "6. HARINGEY HCBS VOIDS - 17 JULY 2023",
  },
  {
    seq: 9,
    project:
      "Notting Hill Genesis, Planned Investment Framework - Lot 2 Kitchens and Bathrooms",
    outcome: "Successful",
    bid_type: "Mini Tender",
    submitted: "2023-08-07",
    quality_score_pct: 64.67,
    quality_tier: "high_quality",
    group: "won",
    outcome_notes: "20 Oct 2023. Confirmed successful.",
    questions: ["Managing Prog Del", "Mobilisation", "Social Value"],
    price_quality_split: "30% Price / 70% Quality",
    qdrant_project_name:
      "9. NOTTING HILL GENESIS - KITCHENS AND BATHROOMS FRAMEWORK - 7 AUGUST 2023",
  },
  {
    seq: 15,
    project:
      "London Borough of Haringey, Housing & Repair Services - Repairs / Disrepairs",
    outcome: "WON",
    bid_type: "Mini Tender",
    submitted: "2023-11-09",
    quality_score_pct: 63.45,
    quality_tier: "high_quality",
    group: "won",
    outcome_notes: "Confirmed won 18 June 2024.",
    questions: ["Mobilisation", "Health & Safety", "Programme Mgmt"],
    price_quality_split: "60% Price / 40% Quality",
    value_gbp: 500_000,
    qdrant_project_name: "15. HARINGEY  REPAIRS & DISREPAIRS 9 NOVEMBER 2023",
  },
  {
    seq: 22,
    project: "Example Consortium, Retrofit Programme — Wave 2",
    outcome: "Lost — Price",
    bid_type: "Framework",
    submitted: "2024-02-14",
    quality_score_pct: 52.3,
    quality_tier: "medium_quality",
    group: "lost",
    outcome_notes: "Strong quality narrative; underbid on price envelope.",
    questions: ["Social Value", "Carbon", "Residents"],
    price_quality_split: "55% Price / 45% Quality",
    qdrant_project_name: "22. EXAMPLE RETROFIT WAVE 2 - FEB 2024",
  },
  {
    seq: 31,
    project: "Regional HA, Planned Works — Kitchen Replacements",
    outcome: "Lost",
    bid_type: "Mini Tender",
    submitted: "2024-06-01",
    quality_score_pct: 38.0,
    quality_tier: "other",
    group: "lost",
    outcome_notes: "Missed several mandatory attachments.",
    questions: ["Quality Control"],
    qdrant_project_name: "31. REGIONAL HA KITCHENS - JUNE 2024",
  },
  {
    seq: 44,
    project: "Town Council, Civic Offices Refurbishment",
    outcome: "Waiting Outcome",
    bid_type: "Restricted",
    submitted: "2025-01-20",
    quality_score_pct: null,
    quality_tier: "other",
    group: "other",
    outcome_notes: "Awaiting moderation outcome.",
    questions: ["Programme", "Health & Safety"],
    qdrant_project_name: "44. TOWN COUNCIL CIVIC - JAN 2025",
  },
];
